# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kumaran/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/kumaran/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kumaran/gdev/cp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kumaran/gdev/cp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/kumaran/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/kumaran/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kumaran/gdev/cp/CMakeFiles /home/kumaran/gdev/cp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kumaran/gdev/cp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cp

# Build rule for target.
cp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cp
.PHONY : cp

# fast build rule for target.
cp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/build
.PHONY : cp/fast

#=============================================================================
# Target rules for targets named lca_binary_lifting

# Build rule for target.
lca_binary_lifting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lca_binary_lifting
.PHONY : lca_binary_lifting

# fast build rule for target.
lca_binary_lifting/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lca_binary_lifting.dir/build.make CMakeFiles/lca_binary_lifting.dir/build
.PHONY : lca_binary_lifting/fast

#=============================================================================
# Target rules for targets named tele

# Build rule for target.
tele: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tele
.PHONY : tele

# fast build rule for target.
tele/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tele.dir/build.make CMakeFiles/tele.dir/build
.PHONY : tele/fast

#=============================================================================
# Target rules for targets named temp2

# Build rule for target.
temp2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 temp2
.PHONY : temp2

# fast build rule for target.
temp2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/temp2.dir/build.make CMakeFiles/temp2.dir/build
.PHONY : temp2/fast

cpp/Algorithms/Tree/lca_binary_lifting.o: cpp/Algorithms/Tree/lca_binary_lifting.cpp.o
.PHONY : cpp/Algorithms/Tree/lca_binary_lifting.o

# target to build an object file
cpp/Algorithms/Tree/lca_binary_lifting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lca_binary_lifting.dir/build.make CMakeFiles/lca_binary_lifting.dir/cpp/Algorithms/Tree/lca_binary_lifting.cpp.o
.PHONY : cpp/Algorithms/Tree/lca_binary_lifting.cpp.o

cpp/Algorithms/Tree/lca_binary_lifting.i: cpp/Algorithms/Tree/lca_binary_lifting.cpp.i
.PHONY : cpp/Algorithms/Tree/lca_binary_lifting.i

# target to preprocess a source file
cpp/Algorithms/Tree/lca_binary_lifting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lca_binary_lifting.dir/build.make CMakeFiles/lca_binary_lifting.dir/cpp/Algorithms/Tree/lca_binary_lifting.cpp.i
.PHONY : cpp/Algorithms/Tree/lca_binary_lifting.cpp.i

cpp/Algorithms/Tree/lca_binary_lifting.s: cpp/Algorithms/Tree/lca_binary_lifting.cpp.s
.PHONY : cpp/Algorithms/Tree/lca_binary_lifting.s

# target to generate assembly for a file
cpp/Algorithms/Tree/lca_binary_lifting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lca_binary_lifting.dir/build.make CMakeFiles/lca_binary_lifting.dir/cpp/Algorithms/Tree/lca_binary_lifting.cpp.s
.PHONY : cpp/Algorithms/Tree/lca_binary_lifting.cpp.s

tele.o: tele.cpp.o
.PHONY : tele.o

# target to build an object file
tele.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tele.dir/build.make CMakeFiles/tele.dir/tele.cpp.o
.PHONY : tele.cpp.o

tele.i: tele.cpp.i
.PHONY : tele.i

# target to preprocess a source file
tele.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tele.dir/build.make CMakeFiles/tele.dir/tele.cpp.i
.PHONY : tele.cpp.i

tele.s: tele.cpp.s
.PHONY : tele.s

# target to generate assembly for a file
tele.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tele.dir/build.make CMakeFiles/tele.dir/tele.cpp.s
.PHONY : tele.cpp.s

temp2.o: temp2.cpp.o
.PHONY : temp2.o

# target to build an object file
temp2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/temp2.dir/build.make CMakeFiles/temp2.dir/temp2.cpp.o
.PHONY : temp2.cpp.o

temp2.i: temp2.cpp.i
.PHONY : temp2.i

# target to preprocess a source file
temp2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/temp2.dir/build.make CMakeFiles/temp2.dir/temp2.cpp.i
.PHONY : temp2.cpp.i

temp2.s: temp2.cpp.s
.PHONY : temp2.s

# target to generate assembly for a file
temp2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/temp2.dir/build.make CMakeFiles/temp2.dir/temp2.cpp.s
.PHONY : temp2.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cp.dir/build.make CMakeFiles/cp.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cp"
	@echo "... lca_binary_lifting"
	@echo "... tele"
	@echo "... temp2"
	@echo "... cpp/Algorithms/Tree/lca_binary_lifting.o"
	@echo "... cpp/Algorithms/Tree/lca_binary_lifting.i"
	@echo "... cpp/Algorithms/Tree/lca_binary_lifting.s"
	@echo "... tele.o"
	@echo "... tele.i"
	@echo "... tele.s"
	@echo "... temp2.o"
	@echo "... temp2.i"
	@echo "... temp2.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

